<a href="https://colab.research.google.com/github/amannayanmujawar/my-firt-project-idata-visualization-of-bitcoin-sentiment-data/blob/main/iphonedataanalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("/content/iphone.csv")

In [4]:
df.shape

(100, 10)

In [5]:
df.columns

Index(['Order_ID', 'Customer_Name', 'Country', 'iPhone_Model', 'Storage',
       'Color', 'Quantity', 'Price', 'Sale_Date', 'Payment_Method'],
      dtype='object')

In [6]:
df.values

array([[1001, 'Customer_1', 'USA', 'iPhone 13', '256GB', 'Purple', 5,
        1817, '01-05-2025', 'Debit Card'],
       [1002, 'Customer_2', 'Canada', 'iPhone 12', '256GB', 'Blue', 1,
        998, '05-03-2025', 'PayPal'],
       [1003, 'Customer_3', 'Canada', 'iPhone 15 Pro Max', '512GB',
        'Black', 5, 876, '25-01-2025', 'Credit Card'],
       [1004, 'Customer_4', 'USA', 'iPhone 15 Pro Max', '512GB', 'Black',
        2, 1290, '24-03-2025', 'Debit Card'],
       [1005, 'Customer_5', 'USA', 'iPhone 15', '128GB', 'Blue', 3, 1092,
        '01-02-2025', 'Debit Card'],
       [1006, 'Customer_6', 'UAE', 'iPhone 14 Pro', '256GB', 'Red', 5,
        1939, '15-02-2025', 'Debit Card'],
       [1007, 'Customer_7', 'Germany', 'iPhone 14 Pro', '512GB', 'Blue',
        1, 1798, '13-02-2025', 'Debit Card'],
       [1008, 'Customer_8', 'UK', 'iPhone 15 Pro Max', '128GB', 'Purple',
        3, 1808, '30-03-2025', 'Debit Card'],
       [1009, 'Customer_9', 'UAE', 'iPhone 12', '512GB', 'Purple', 2,
        1381, '06-03-2025', 'Debit Card'],
       [1010, 'Customer_10', 'Pakistan', 'iPhone 14 Pro', '128GB', 'Red',
        5, 1670, '25-02-2025', 'Debit Card'],
       [1011, 'Customer_11', 'UK', 'iPhone 15 Pro Max', '256GB', 'White',
        5, 1857, '28-01-2025', 'PayPal'],
       [1012, 'Customer_12', 'USA', 'iPhone 14', '128GB', 'Black', 3,
        1572, '25-03-2025', 'Cash'],
       [1013, 'Customer_13', 'Germany', 'iPhone 12', '512GB', 'Blue', 3,
        1868, '18-02-2025', 'PayPal'],
       [1014, 'Customer_14', 'USA', 'iPhone 12', '512GB', 'Black', 3,
        1743, '17-01-2025', 'Credit Card'],
       [1015, 'Customer_15', 'UAE', 'iPhone 14 Pro', '256GB', 'Blue', 1,
        1544, '27-01-2025', 'Credit Card'],
       [1016, 'Customer_16', 'UAE', 'iPhone 12', '128GB', 'Blue', 4,
        1819, '04-04-2025', 'Debit Card'],
       [1017, 'Customer_17', 'Germany', 'iPhone 13', '512GB', 'Red', 5,
        1992, '28-04-2025', 'PayPal'],
       [1018, 'Customer_18', 'Canada', 'iPhone 14 Pro', '256GB', 'Red',
        2, 1003, '04-04-2025', 'PayPal'],
       [1019, 'Customer_19', 'UAE', 'iPhone 13', '128GB', 'Purple', 1,
        1010, '15-03-2025', 'Debit Card'],
       [1020, 'Customer_20', 'UAE', 'iPhone 15', '256GB', 'Purple', 3,
        1588, '27-03-2025', 'Debit Card'],
       [1021, 'Customer_21', 'Pakistan', 'iPhone 15', '256GB', 'Red', 3,
        742, '12-03-2025', 'Cash'],
       [1022, 'Customer_22', 'Pakistan', 'iPhone 15', '128GB', 'Black',
        4, 1627, '22-03-2025', 'PayPal'],
       [1023, 'Customer_23', 'USA', 'iPhone 15', '128GB', 'Red', 5, 1964,
        '19-04-2025', 'Cash'],
       [1024, 'Customer_24', 'UK', 'iPhone 15', '256GB', 'White', 4, 817,
        '01-01-2025', 'Cash'],
       [1025, 'Customer_25', 'UK', 'iPhone 15 Pro Max', '128GB',
        'Purple', 5, 1571, '23-01-2025', 'Debit Card'],
       [1026, 'Customer_26', 'UAE', 'iPhone 14', '128GB', 'Red', 3, 1302,
        '27-03-2025', 'Debit Card'],
       [1027, 'Customer_27', 'USA', 'iPhone 13', '256GB', 'White', 5,
        1060, '19-01-2025', 'Cash'],
       [1028, 'Customer_28', 'UK', 'iPhone 13', '128GB', 'Blue', 4, 1879,
        '30-01-2025', 'Credit Card'],
       [1029, 'Customer_29', 'Canada', 'iPhone 14 Pro', '256GB', 'Red',
        3, 1963, '30-03-2025', 'Debit Card'],
       [1030, 'Customer_30', 'Canada', 'iPhone 14', '512GB', 'Blue', 5,
        1673, '19-01-2025', 'Debit Card'],
       [1031, 'Customer_31', 'UAE', 'iPhone 13', '256GB', 'Purple', 5,
        1135, '26-03-2025', 'Debit Card'],
       [1032, 'Customer_32', 'USA', 'iPhone 15 Pro Max', '128GB', 'Blue',
        5, 1550, '09-03-2025', 'PayPal'],
       [1033, 'Customer_33', 'Canada', 'iPhone 14', '128GB', 'Blue', 5,
        1646, '05-02-2025', 'PayPal'],
       [1034, 'Customer_34', 'USA', 'iPhone 14 Pro', '128GB', 'Red', 4,
        1559, '17-03-2025', 'Debit Card'],
       [1035, 'Customer_35', 'Canada', 'iPhone 14 Pro', '128GB', 'White',
        5, 1793, '02-01-2025', 'Cash'],
       [1036, 'Customer_36', 'USA', 'iPhone 12', '512GB', 'Blue', 5,
        1030, '02-04-2025', 'Credit Card'],
       [1037, 'Customer_37', 'Canada', 'iPhone 14 Pro', '128GB', 'Red',
        2, 1921, '09-04-2025', 'Credit Card'],
       [1038, 'Customer_38', 'UAE', 'iPhone 14 Pro', '128GB', 'Purple',
        1, 1674, '17-04-2025', 'Credit Card'],
       [1039, 'Customer_39', 'Canada', 'iPhone 15 Pro Max', '256GB',
        'Red', 1, 1218, '25-01-2025', 'Credit Card'],
       [1040, 'Customer_40', 'UAE', 'iPhone 15 Pro Max', '256GB',
        'Purple', 4, 1034, '01-05-2025', 'Credit Card'],
       [1041, 'Customer_41', 'UK', 'iPhone 15', '128GB', 'Black', 3,
        1633, '27-03-2025', 'Credit Card'],
       [1042, 'Customer_42', 'UK', 'iPhone 15', '256GB', 'Black', 4, 720,
        '20-01-2025', 'Debit Card'],
       [1043, 'Customer_43', 'UAE', 'iPhone 15', '128GB', 'Red', 2, 1238,
        '22-03-2025', 'Credit Card'],
       [1044, 'Customer_44', 'USA', 'iPhone 13', '256GB', 'White', 4,
        1779, '12-01-2025', 'Debit Card'],
       [1045, 'Customer_45', 'UK', 'iPhone 13', '256GB', 'Purple', 5,
        1667, '18-04-2025', 'Debit Card'],
       [1046, 'Customer_46', 'Germany', 'iPhone 15 Pro Max', '512GB',
        'Blue', 1, 1094, '12-01-2025', 'PayPal'],
       [1047, 'Customer_47', 'USA', 'iPhone 12', '256GB', 'White', 5,
        1120, '11-01-2025', 'PayPal'],
       [1048, 'Customer_48', 'USA', 'iPhone 14', '256GB', 'Black', 5,
        1786, '28-03-2025', 'Cash'],
       [1049, 'Customer_49', 'Canada', 'iPhone 14', '128GB', 'Black', 1,
        1199, '27-03-2025', 'Debit Card'],
       [1050, 'Customer_50', 'Canada', 'iPhone 14 Pro', '128GB', 'Blue',
        1, 733, '12-01-2025', 'Cash'],
       [1051, 'Customer_51', 'UK', 'iPhone 15 Pro Max', '256GB', 'Blue',
        5, 1113, '22-01-2025', 'Credit Card'],
       [1052, 'Customer_52', 'Pakistan', 'iPhone 14', '512GB', 'Blue', 5,
        764, '12-03-2025', 'Debit Card'],
       [1053, 'Customer_53', 'USA', 'iPhone 14 Pro', '128GB', 'Black', 1,
        1959, '27-02-2025', 'PayPal'],
       [1054, 'Customer_54', 'UK', 'iPhone 14', '256GB', 'White', 1,
        1829, '24-04-2025', 'Credit Card'],
       [1055, 'Customer_55', 'Pakistan', 'iPhone 14 Pro', '128GB',
        'Blue', 2, 899, '10-04-2025', 'PayPal'],
       [1056, 'Customer_56', 'USA', 'iPhone 15', '512GB', 'Black', 5,
        1250, '02-01-2025', 'Debit Card'],
       [1057, 'Customer_57', 'Pakistan', 'iPhone 14 Pro', '256GB',
        'Blue', 1, 945, '01-05-2025', 'Debit Card'],
       [1058, 'Customer_58', 'UK', 'iPhone 15 Pro Max', '256GB',
        'Purple', 5, 1752, '11-04-2025', 'Debit Card'],
       [1059, 'Customer_59', 'Pakistan', 'iPhone 14 Pro', '512GB', 'Red',
        4, 1909, '13-04-2025', 'Debit Card'],
       [1060, 'Customer_60', 'Germany', 'iPhone 14 Pro', '512GB', 'Blue',
        5, 1714, '12-01-2025', 'Credit Card'],
       [1061, 'Customer_61', 'UAE', 'iPhone 15', '512GB', 'Black', 5,
        1519, '21-02-2025', 'Debit Card'],
       [1062, 'Customer_62', 'Canada', 'iPhone 13', '512GB', 'Purple', 4,
        1769, '05-04-2025', 'PayPal'],
       [1063, 'Customer_63', 'Canada', 'iPhone 15 Pro Max', '128GB',
        'White', 5, 1644, '21-02-2025', 'Credit Card'],
       [1064, 'Customer_64', 'UK', 'iPhone 15 Pro Max', '512GB', 'Red',
        2, 1991, '28-01-2025', 'Cash'],
       [1065, 'Customer_65', 'Canada', 'iPhone 14', '256GB', 'White', 3,
        1706, '04-01-2025', 'Debit Card'],
       [1066, 'Customer_66', 'USA', 'iPhone 14', '256GB', 'White', 1,
        1884, '28-03-2025', 'Debit Card'],
       [1067, 'Customer_67', 'Canada', 'iPhone 14 Pro', '128GB', 'Blue',
        3, 1027, '22-04-2025', 'Debit Card'],
       [1068, 'Customer_68', 'Pakistan', 'iPhone 15 Pro Max', '128GB',
        'Black', 2, 788, '05-04-2025', 'Credit Card'],
       [1069, 'Customer_69', 'Germany', 'iPhone 14 Pro', '128GB',
        'White', 3, 796, '25-01-2025', 'PayPal'],
       [1070, 'Customer_70', 'Canada', 'iPhone 14 Pro', '512GB', 'Blue',
        4, 1829, '13-01-2025', 'Credit Card'],
       [1071, 'Customer_71', 'UK', 'iPhone 12', '512GB', 'Purple', 2,
        1977, '10-01-2025', 'Cash'],
       [1072, 'Customer_72', 'UAE', 'iPhone 12', '128GB', 'Red', 5, 1964,
        '06-02-2025', 'Debit Card'],
       [1073, 'Customer_73', 'USA', 'iPhone 14 Pro', '128GB', 'Red', 2,
        1629, '28-01-2025', 'Cash'],
       [1074, 'Customer_74', 'Germany', 'iPhone 15 Pro Max', '256GB',
        'White', 1, 1987, '25-04-2025', 'PayPal'],
       [1075, 'Customer_75', 'Germany', 'iPhone 14', '512GB', 'Blue', 4,
        1547, '10-01-2025', 'Cash'],
       [1076, 'Customer_76', 'UK', 'iPhone 14 Pro', '256GB', 'Red', 5,
        1923, '12-04-2025', 'Cash'],
       [1077, 'Customer_77', 'UAE', 'iPhone 14 Pro', '512GB', 'Blue', 2,
        1477, '27-02-2025', 'PayPal'],
       [1078, 'Customer_78', 'Pakistan', 'iPhone 13', '128GB', 'Purple',
        4, 1464, '15-01-2025', 'Cash'],
       [1079, 'Customer_79', 'USA', 'iPhone 15', '128GB', 'Purple', 3,
        1790, '12-02-2025', 'Credit Card'],
       [1080, 'Customer_80', 'USA', 'iPhone 15', '512GB', 'Purple', 4,
        1819, '24-02-2025', 'Debit Card'],
       [1081, 'Customer_81', 'Pakistan', 'iPhone 13', '256GB', 'Purple',
        5, 1579, '05-03-2025', 'Credit Card'],
       [1082, 'Customer_82', 'UK', 'iPhone 15 Pro Max', '256GB', 'Blue',
        1, 756, '28-03-2025', 'Debit Card'],
       [1083, 'Customer_83', 'UK', 'iPhone 14 Pro', '128GB', 'White', 3,
        1165, '08-03-2025', 'Cash'],
       [1084, 'Customer_84', 'Germany', 'iPhone 13', '256GB', 'Red', 5,
        1229, '22-03-2025', 'Cash'],
       [1085, 'Customer_85', 'UK', 'iPhone 12', '256GB', 'White', 4,
        1656, '12-04-2025', 'Cash'],
       [1086, 'Customer_86', 'Germany', 'iPhone 12', '256GB', 'Black', 2,
        950, '08-04-2025', 'Cash'],
       [1087, 'Customer_87', 'Canada', 'iPhone 15', '128GB', 'White', 1,
        1903, '02-01-2025', 'PayPal'],
       [1088, 'Customer_88', 'UK', 'iPhone 15 Pro Max', '512GB',
        'Purple', 5, 718, '04-02-2025', 'Cash'],
       [1089, 'Customer_89', 'USA', 'iPhone 13', '256GB', 'White', 3,
        1249, '12-01-2025', 'Debit Card'],
       [1090, 'Customer_90', 'USA', 'iPhone 12', '256GB', 'White', 3,
        887, '17-02-2025', 'Debit Card'],
       [1091, 'Customer_91', 'UAE', 'iPhone 15', '256GB', 'Red', 5, 1357,
        '22-03-2025', 'PayPal'],
       [1092, 'Customer_92', 'UAE', 'iPhone 15 Pro Max', '256GB',
        'White', 3, 1361, '10-02-2025', 'Credit Card'],
       [1093, 'Customer_93', 'UK', 'iPhone 12', '256GB', 'Black', 3,
        1971, '20-01-2025', 'Credit Card'],
       [1094, 'Customer_94', 'USA', 'iPhone 15 Pro Max', '512GB',
        'White', 1, 1622, '22-03-2025', 'Credit Card'],
       [1095, 'Customer_95', 'Canada', 'iPhone 13', '128GB', 'White', 4,
        1388, '06-01-2025', 'Credit Card'],
       [1096, 'Customer_96', 'UAE', 'iPhone 14 Pro', '256GB', 'Blue', 1,
        1743, '09-03-2025', 'Credit Card'],
       [1097, 'Customer_97', 'UK', 'iPhone 15 Pro Max', '512GB', 'White',
        3, 1671, '08-02-2025', 'Credit Card'],
       [1098, 'Customer_98', 'UK', 'iPhone 15 Pro Max', '512GB', 'White',
        4, 1125, '08-01-2025', 'Debit Card'],
       [1099, 'Customer_99', 'Germany', 'iPhone 15 Pro Max', '512GB',
        'Purple', 5, 1540, '04-02-2025', 'Debit Card'],
       [1100, 'Customer_100', 'UK', 'iPhone 15', '512GB', 'Blue', 3,
        1549, '28-03-2025', 'Debit Card']], dtype=object)

In [7]:
df.index

RangeIndex(start=0, stop=100, step=1)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        100 non-null    int64
 1   Customer_Name   100 non-null    object
 2   Country         100 non-null    object
 3   iPhone_Model    100 non-null    object
 4   Storage         100 non-null    object
 5   Color           100 non-null    object
 6   Quantity        100 non-null    int64
 7   Price           100 non-null    int64
 8   Sale_Date       100 non-null    object
 9   Payment_Method  100 non-null    object
dtypes: int64(3), object(7)
memory usage: 7.9+ KB

In [9]:
df.isnull().sum()

Order_ID          0
Customer_Name     0
Country           0
iPhone_Model      0
Storage           0
Color             0
Quantity          0
Price             0
Sale_Date         0
Payment_Method    0
dtype: int64

In [10]:
df.notnull().sum()

Order_ID          100
Customer_Name     100
Country           100
iPhone_Model      100
Storage           100
Color             100
Quantity          100
Price             100
Sale_Date         100
Payment_Method    100
dtype: int64

In [12]:
df.describe()

          Order_ID    Quantity        Price
count   100.000000  100.000000   100.000000
mean   1050.500000    3.330000  1468.750000
std      29.011492    1.484295   388.367637
min    1001.000000    1.000000   718.000000
25%    1025.750000    2.000000  1123.750000
50%    1050.500000    3.000000  1571.500000
75%    1075.250000    5.000000  1794.250000
max    1100.000000    5.000000  1992.000000

In [14]:
df.count()

Order_ID          100
Customer_Name     100
Country           100
iPhone_Model      100
Storage           100
Color             100
Quantity          100
Price             100
Sale_Date         100
Payment_Method    100
dtype: int64

In [17]:
df.head()

,Order_ID,Customer_Name,Country,iPhone_Model,Storage,Color,Quantity,Price,Sale_Date,Payment_Method
0,1001,Customer_1,USA,iPhone 13,256GB,Purple,5,1817,01-05-2025,Debit Card
1,1002,Customer_2,Canada,iPhone 12,256GB,Blue,1,998,05-03-2025,PayPal
2,1003,Customer_3,Canada,iPhone 15 Pro Max,512GB,Black,5,876,25-01-2025,Credit Card
3,1004,Customer_4,USA,iPhone 15 Pro Max,512GB,Black,2,1290,24-03-2025,Debit Card
4,1005,Customer_5,USA,iPhone 15,128GB,Blue,3,1092,01-02-2025,Debit Card

In [20]:
df.tail()

,Order_ID,Customer_Name,Country,iPhone_Model,Storage,Color,Quantity,Price,Sale_Date,Payment_Method
95,1096,Customer_96,UAE,iPhone 14 Pro,256GB,Blue,1,1743,09-03-2025,Credit Card
96,1097,Customer_97,UK,iPhone 15 Pro Max,512GB,White,3,1671,08-02-2025,Credit Card
97,1098,Customer_98,UK,iPhone 15 Pro Max,512GB,White,4,1125,08-01-2025,Debit Card
98,1099,Customer_99,Germany,iPhone 15 Pro Max,512GB,Purple,5,1540,04-02-2025,Debit Card
99,1100,Customer_100,UK,iPhone 15,512GB,Blue,3,1549,28-03-2025,Debit Card

**Accessing the data from dataframe**

In [21]:
df.columns

Index(['Order_ID', 'Customer_Name', 'Country', 'iPhone_Model', 'Storage',
       'Color', 'Quantity', 'Price', 'Sale_Date', 'Payment_Method'],
      dtype='object')

In [ ]:
df[]